#+---------+
#+ Options +
#+---------+
set -g status-interval 1
set -g status on

#+--------+
#+ Status +
#+--------+
#+--- Layout ---+
set -g status-justify left

#+--- Colors ---+
set -g status-style bg=$TMUX_BG,fg=$TMUX_TAB_FG

#+-------+
#+ Panes +
#+-------+
set -g pane-border-style bg=$TMUX_BG,fg=$TMUX_TAB_BG
set -g pane-active-border-style bg=$TMUX_BG,fg=$TMUX_ACTIVE_BG
set -g display-panes-colour $TMUX_TAB_BG
set -g display-panes-active-colour $TMUX_ACTIVE_BG

#+------------+
#+ Clock Mode +
#+------------+
setw -g clock-mode-colour $TMUX_ACTIVE_BG

#+----------+
#+ Messages +
#+----------+
set -g message-style bg=$TMUX_TAB_BG,fg=$TMUX_TAB_FG
set -g message-command-style  bg=$TMUX_TAB_BG,fg=$TMUX_TAB_FG

#+--------+
#+ Status +
#+--------+
#+--- Bars ---+
set -g status-left "#[fg=$TMUX_ACTIVE_BG,bg=$TMUX_BG]#[fg=$TMUX_ACTIVE_FG,bg=$TMUX_ACTIVE_BG]#S#[fg=$TMUX_ACTIVE_BG,bg=$TMUX_BG] "
set -g status-right "#{?client_prefix,#[fg=$TMUX_ACTIVE_BG]#[bg=$TMUX_BG]#[fg=$TMUX_ACTIVE_FG]#[bg=$TMUX_ACTIVE_BG]C-a#[fg=$TMUX_ACTIVE_BG]#[bg=$TMUX_BG]#[bg=$TMUX_BG] ,} #[fg=$TMUX_ACTIVE_BG,bg=$TMUX_BG]#[fg=$TMUX_ACTIVE_FG,bg=$TMUX_ACTIVE_BG]#H#[fg=$TMUX_ACTIVE_BG,bg=$TMUX_BG] "

#+--- Windows ---+
set -g window-status-format "#[fg=$TMUX_TAB_BG,bg=$TMUX_BG]#[fg=$TMUX_TAB_FG,bg=$TMUX_TAB_BG]#I │ #W #F#[fg=$TMUX_TAB_BG,bg=$TMUX_BG] "
set -g window-status-current-format "#[fg=$TMUX_ACTIVE_BG,bg=$TMUX_BG]#[fg=$TMUX_ACTIVE_FG,bg=$TMUX_ACTIVE_BG]#I │ #W #F#[fg=$TMUX_ACTIVE_BG,bg=$TMUX_BG] "
set -g window-status-separator ""
set -g window-status-activity-style ""
